export const LOGIN_ACTION_SEND_REQUEST = "[LOGIN ACTION] SEND REQUEST";
export const LOGIN_ACTION_SET_ALTER = "[LOGIN ACTION] SET ALTER";
export const LOGIN_ACTION_SET_ERROR = "[LOGIN ACTION] SET ERROR";
export const LOGIN_ACTION_SET_STATUS = "[LOGIN ACTION] SET STATUS";