export const PROFILE_ACTION_GET_USER = "[PROFILE ACTION] GET USER";
export const PROFILE_ACTION_SET_USER = "[PROFILE ACTION] SET USER";
export const PROFILE_ACTION_SET_DATA = "[PROFILE ACTION] SET DATA";