export const PROFILE_ACTION_GET_USER = "[PROFILE ACTION] GET USER";
export const PROFILE_ACTION_SET_USER = "[PROFILE ACTION] SET USER";
export const PROFILE_ACTION_SET_DATA = "[PROFILE ACTION] SET DATA";
export const AUTH_ACTION_CHECK_LOGIN = "[AUTH ACTION] CHECK";
export const AUTH_ACTION_LOGGED = "[AUTH ACTION] LOGGED";
export const AUTH_ACTION_LOGOUT = "[AUTH ACTION] LOGOUT";