export const REGISTER_ACTION_SET_ERROR = "[REGISTER ACTION] SET ERROR";
export const REGISTER_ACTION_SET_INPUT = "[REGISTER ACTION] SET INPUT";
export const REGISTER_ACTION_SEND_REQUEST = "[REGISTER ACTION] SEND REQUEST";
export const REGISTER_ACTION_SET_STATUS = "[REGISTER ACTION] SET STATUS";
export const REGISTER_ACTION_SET_ALTER = "[REGISTER ACTION] SET ALTER";